import pytest
from vacancy import Vacancy


def test_cast_to_object_list():
    vacancy = Vacancy('Консультант по ИИ для написания технического задания (ТЗ)', 'https://api.hh.ru/vacancies/102489051?host=hh.ru', 120000, 300000, 'RUR', 'Доказанный опыт в проектах по ИИ и машинному обучению. Экспертиза в использовании облачных платформ ИИ, таких как Google Recommendations AI...')
    result = Vacancy.cast_to_object_list([{'id': '102489051', 'premium': False, 'name': 'Консультант по ИИ для написания технического задания (ТЗ)', 'department': None, 'has_test': False, 'response_letter_required': False, 'area': {'id': '1', 'name': 'Москва', 'url': 'https://api.hh.ru/areas/1'}, 'salary': {'from': 120000, 'to': 300000, 'currency': 'RUR', 'gross': False}, 'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None, 'published_at': '2024-06-22T19:40:21+0300', 'created_at': '2024-06-22T19:40:21+0300', 'archived': False, 'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=102489051', 'show_logo_in_search': None, 'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/102489051?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/102489051', 'relations': [], 'employer': {'id': '9537245', 'name': 'Move2Armenia', 'url': 'https://api.hh.ru/employers/9537245', 'alternate_url': 'https://hh.ru/employer/9537245', 'logo_urls': {'original': 'https://img.hhcdn.ru/employer-logo-original/1053930.jpeg', '90': 'https://img.hhcdn.ru/employer-logo/5836361.jpeg', '240': 'https://img.hhcdn.ru/employer-logo/5836362.jpeg'}, 'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=9537245', 'accredited_it_employer': False, 'trusted': True}, 'snippet': {'requirement': 'Доказанный опыт в проектах по ИИ и машинному обучению. Экспертиза в использовании облачных платформ ИИ, таких как Google Recommendations AI...', 'responsibility': 'Анализ текущей структуры приложения и требований пользователей. Разработка подробного ТЗ для интеграции ИИ, включая требования к данным, спецификации моделей и...'}, 'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False, 'professional_roles': [{'id': '165', 'name': 'Дата-сайентист'}], 'accept_incomplete_resumes': False, 'experience': {'id': 'between3And6', 'name': 'От 3 до 6 лет'}, 'employment': {'id': 'part', 'name': 'Частичная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False, 'adv_context': None}])
    assert str(vacancy) == str(result[0])

    vacancy = Vacancy('Консультант по ИИ для написания технического задания (ТЗ)', 'https://api.hh.ru/vacancies/102489051?host=hh.ru', 0, 0, '', 'Доказанный опыт в проектах по ИИ и машинному обучению. Экспертиза в использовании облачных платформ ИИ, таких как Google Recommendations AI...')
    result = list(Vacancy.cast_to_object_list([{'id': '102489051', 'premium': False, 'name': 'Консультант по ИИ для написания технического задания (ТЗ)', 'department': None, 'has_test': False, 'response_letter_required': False, 'area': {'id': '1', 'name': 'Москва', 'url': 'https://api.hh.ru/areas/1'}, 'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None, 'published_at': '2024-06-22T19:40:21+0300', 'created_at': '2024-06-22T19:40:21+0300', 'archived': False, 'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=102489051', 'show_logo_in_search': None, 'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/102489051?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/102489051', 'relations': [], 'employer': {'id': '9537245', 'name': 'Move2Armenia', 'url': 'https://api.hh.ru/employers/9537245', 'alternate_url': 'https://hh.ru/employer/9537245', 'logo_urls': {'original': 'https://img.hhcdn.ru/employer-logo-original/1053930.jpeg', '90': 'https://img.hhcdn.ru/employer-logo/5836361.jpeg', '240': 'https://img.hhcdn.ru/employer-logo/5836362.jpeg'}, 'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=9537245', 'accredited_it_employer': False, 'trusted': True}, 'snippet': {'requirement': 'Доказанный опыт в проектах по ИИ и машинному обучению. Экспертиза в использовании облачных платформ ИИ, таких как Google Recommendations AI...', 'responsibility': 'Анализ текущей структуры приложения и требований пользователей. Разработка подробного ТЗ для интеграции ИИ, включая требования к данным, спецификации моделей и...'}, 'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False, 'professional_roles': [{'id': '165', 'name': 'Дата-сайентист'}], 'accept_incomplete_resumes': False, 'experience': {'id': 'between3And6', 'name': 'От 3 до 6 лет'}, 'employment': {'id': 'part', 'name': 'Частичная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False, 'adv_context': None}]))
    assert str(vacancy) == str(result[0])

    vacancy = Vacancy('', 'https://api.hh.ru/vacancies/102489051?host=hh.ru', 0, 0, '', 'Доказанный опыт в проектах по ИИ и машинному обучению. Экспертиза в использовании облачных платформ ИИ, таких как Google Recommendations AI...')
    result = list(Vacancy.cast_to_object_list([{'id': '102489051', 'premium': False, 'department': None, 'has_test': False, 'response_letter_required': False, 'area': {'id': '1', 'name': 'Москва', 'url': 'https://api.hh.ru/areas/1'}, 'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None, 'published_at': '2024-06-22T19:40:21+0300', 'created_at': '2024-06-22T19:40:21+0300', 'archived': False, 'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=102489051', 'show_logo_in_search': None, 'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/102489051?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/102489051', 'relations': [], 'employer': {'id': '9537245', 'name': 'Move2Armenia', 'url': 'https://api.hh.ru/employers/9537245', 'alternate_url': 'https://hh.ru/employer/9537245', 'logo_urls': {'original': 'https://img.hhcdn.ru/employer-logo-original/1053930.jpeg', '90': 'https://img.hhcdn.ru/employer-logo/5836361.jpeg', '240': 'https://img.hhcdn.ru/employer-logo/5836362.jpeg'}, 'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=9537245', 'accredited_it_employer': False, 'trusted': True}, 'snippet': {'requirement': 'Доказанный опыт в проектах по ИИ и машинному обучению. Экспертиза в использовании облачных платформ ИИ, таких как Google Recommendations AI...', 'responsibility': 'Анализ текущей структуры приложения и требований пользователей. Разработка подробного ТЗ для интеграции ИИ, включая требования к данным, спецификации моделей и...'}, 'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False, 'professional_roles': [{'id': '165', 'name': 'Дата-сайентист'}], 'accept_incomplete_resumes': False, 'experience': {'id': 'between3And6', 'name': 'От 3 до 6 лет'}, 'employment': {'id': 'part', 'name': 'Частичная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False, 'adv_context': None}]))
    assert str(vacancy) == str(result[0])